EntoSp = {
'to/at': 'á', 
'to love': 'amar', 
'the tree': 'el árbol', 
'the boots': 'las botas', 
'the captain': 'el capitán', 
'the shirt': 'la camisa', 
'the coat': 'la casaca', 
'to buy': 'comprar', 
'the flower': 'la flor', 
'the man': 'el hombre', 
'the brother': 'el hermano', 
'the sister': 'la hermana', 
'the young man': 'el joven', 
'the young woman': 'la joven', 
'the pencil': 'el lápiz', 
'the book': 'el libro', 
'the mother': 'la madre', 
'but': 'pero', 
'more': 'más', 
'the woman': 'la mujer', 
'we have': 'nosotros tenemos', 
'gold': 'el oro', 
'the father': 'el padre', 
'the trousers': 'los pantalones', 
'the paper': 'el papel', 
'for/by': 'para', 
'silver': 'la plata', 
'the pen': 'la pluma', 
'the hat': 'el sombrero', 
'he has': 'él tiene', 
'you (sing.) have': 'V. tiene', 
'you (pl.) have': 'Vs. tienen', 
'the ink': 'la tinta', 
'the inkstand': 'el tintero', 
'to have/to possess': 'tener', 
'I have': 'yo tengo', 
'the old man': 'el viejo', 
'the old woman': 'la vieja', 
'virtue': 'la virtud', 
'German': 'alemán', 
'to drink': 'beber', 
'well': 'bien', 
'coffee': 'café', 
'beer': 'cerveza', 
'carnation': 'clavel', 
'client/customer': 'cliente', 
'to eat': 'comer', 
'to write': 'escribir', 
'to study': 'estudiar', 
'to export': 'exportar', 
'foreigner': 'extranjero', 
'ironware': 'ferretería', 
'large': 'grandes(pl)', 
'son': 'hijo', 
'daughter': 'hija', 
'Italian': 'italiano', 
'gardener': 'jardinero', 
'to read': 'leer', 
'morning/to-morrow': 'mañana', 
'apple': 'manzana', 
'machine': 'máquina', 
'table': 'mesa', 
'my': 'mi', 
'much': 'mucha (f.)', 
'very': 'muy', 
'pear': 'pera', 
'poor': 'pobre', 
'what?': '¿qué?', 
'that/who/which': 'que', 
'rose': 'rosa', 
'his/her/their': 'su', 
'your': 'el … de V.', 
'tea': 'té', 
'wine': 'vino', 
'violet': 'violeta', 
'there': 'allí', 
'here': 'aquí', 
'to look for': 'buscar', 
'horse': 'caballo', 
'box/case': 'caja', 
'the capital/money': 'el capital', 
'the capital/town': 'la capital', 
'to understand': 'comprender', 
'copybook': 'copiador', 
'to believe/to think': 'creer', 
'clerk': 'dependiente', 
'invoice': 'factura', 
'bale': 'fardo', 
'Frenchman': 'Francés', 
'to draw/(a bill of exchange)': 'girar', 
'the language': 'el idioma', 
'Englishman': 'Inglés', 
'intelligence': 'inteligencia', 
'badly': 'mal', 
'muslin': 'muselina', 
'never': 'nunca', 
'country': 'país', 
'little (adj.)': 'pequeño', 
'little (adv. and subs.)': 'poco', 
'the flower-stand': 'el porta-ramillete or florero', 
'who? whom?': '¿quién?', 
'silk': 'seda', 
'partner': 'socio', 
'only': 'sólo/solamente (adv.)', 
'(adv.) only': 'sólo', 
'the exercise': 'el tema', 
'active': 'activo', 
'now': 'ahora', 
'a year': 'un año', 
'that': 'aquella/esa (f.)', 
'baize': 'bayeta', 
'celebrated': 'célebre', 
'top': 'cima', 
'men-servants': 'criados', 
'maid-servants': 'criadas', 
'the day': 'el día', 
'army': 'ejército', 
'bound/(of books)': 'encuadernado', 
'writing-desk': 'escritorio', 
'the matches': 'los fósforos', 
'Wales': 'Gales', 
'youth/young age.': '', 
'the sealing-wax': 'el lacre', 
'reading': 'lectura', 
'to clean': 'limpiar', 
'clean': 'limpio', 
'especially': 'mayormente', 
'doctor': 'médico', 
'the mountain': 'el monte', 
'the snow': 'la nieve', 
'therefore': 'por tanto', 
'door': 'puerta', 
'always': 'siempre', 
'sincere': 'sincero', 
'soldier': 'soldado', 
'velvet': 'terciopelo', 
'candle': 'vela', 
'window': 'ventana', 
'some or any (s.)': 'alguno-a', 
'some or any (pl.)': 'algunos-as', 
'yellow': 'amarillo', 
'beard': 'barba/barbas', 
'chin': 'barbilla/barba', 
'white': 'blanco', 
'mouth': 'boca', 
'hair': 'cabello', 
'head': 'cabeza', 
'brown/(dyed)': '', 
'brush': 'cepillo', 
'any (affirmative)': 'cualesquiera (pl.)', 
'teeth': 'dientes', 
'money': 'dinero', 
'red': 'encarnado', 
'broom': 'escoba', 
'to print (calico)': 'estampar', 
'the forehead': 'la frente', 
'tongue': 'lengua', 
'bad/wicked': 'malo', 
'butter': 'manteca', 
'brown/(natural colour)': 'moreno', 
'nose': '(la) nariz', 
'to want/to need/to be in want of.': 'necesitar', 
'any (after a negative)': 'ningunos-as (pl.)', 
'the eye': 'el ojo', 
'parents': 'padres', 
'calico': 'percal', 
'we want ': 'queremos', 
'to want/to wish to have': 'querer', 
'they want': 'ellos quieren', 
'I want': 'yo quiero', 
'you want': 'V. quiere', 
'ruler': 'regla', 
'if': 'si', 
'complexion': 'la tez', 
'a little/some/or any': 'un poco de', 
'green': 'verde', 
'to have just': 'acabar de', 
'warehouse': 'almacén', 
'to learn': 'aprender', 
'to help': 'ayudar', 
'to wet/to bathe/to water': 'bañar', 
'bicycle': 'bicicleta', 
'most certain': 'certísimo', 
'pupil': 'discípulo', 
'to enjoy': 'disfrutar', 
'it is': 'él es/ella es', 
'it': 'ello (neuter)', 
'this': 'esto (neuter)', 
'these': 'estos (m.)/estas (f.)', 
'the date': 'la fecha', 
'the people': 'la gente', 
'beautifully': 'hermosamente', 
'importance': 'importancia', 
'India': 'La India', 
'free': 'libre', 
'master/teacher': '', 
'most/the majority': '', 
'the month': 'el mes', 
'same': 'mismo', 
'brand new': 'novísimo', 
'other/another': 'otro', 
'River Seine': 'el Sena', 
'River Tagus': 'el Tajo', 
'River Thames': 'el Támesis', 
'also/too': 'también', 
'shop': 'tienda', 
'advantag': 'ventaja', 
'wholesale/retail': 'al por mayor/por menor', 
'rice': 'arroz', 
'article': 'artículo', 
'trade union': 'asociación de obreros', 
'to bleach': 'blanquear', 
'I understand/I see': 'ya caigo', 
'to place': 'colocar', 
'to ge': 'conseguir', 
'consignment': 'consignación', 
'content': 'contenido', 
'decadence': 'decadencia', 
'delegate': 'delegado', 
'too/too much': 'demasiado', 
'difficult': 'difícil', 
'figured drill': 'driles labrados', 
'plain drill': 'driles lisos', 
'to begin to reign': 'entrar á reinar', 
'to choose/to select': 'escoger/elegir', 
'strange/queer/funny': 'extraño', 
'the germ': 'el germen', 
'thick/stout': 'grueso', 
'to find': 'hallar', 
'enlightened': 'ilustrado', 
'enclosing': 'incluyendo', 
'to limit': 'limitar', 
'meanwhile': 'mientrastanto', 
'to get': 'obtener', 
'weight': 'peso', 
'power': 'poder', 
'we should be able to/might/could': 'podríamos', 
'next': 'próximo', 
'abatement': 'rebaja', 
'reduce/to abate': 'rebajar/reducir', 
'abatement/reduction': 'reducción', 
'meeting': 'reunión', 
'to come/to go/out': 'salir', 
'to come to': 'salir en', 
'alone': 'solo (adj.)', 
'subject to': 'sujeto á', 
'to add': 'sumar', 
'bacon': 'tocino', 
'to take': 'tomar', 
'several': 'varios', 
'to take place': 'verificarse', 
'to be compelled to': 'verse obligado á', 
'present': 'actual', 
'I understand/I see': 'Yo Caigo', 
'contents': 'contenido', 
'too/too much': '', 
'figured drills': 'driles labrados', 
'plain drills': 'driles lisos', 
'bound: (of books)': 'encuadernado', 
'youth: young age.': 'juventud', 
'brown: (dyed)': 'café/castaño', 
'master: teacher': 'maestro', 
'most: the majority': 'la mayor parte', 
'I understand: I see': 'ya caigo', 
'too: too much': 'demasiado'
}