SptoEn = {
'á': 'to/at',
'amar': 'to love',
'el árbol': 'the tree',
'las botas': 'the boots',
'el capitán': 'the captain',
'la camisa': 'the shirt',
'la casaca': 'the coat',
'comprar': 'to buy',
'la flor': 'the flower',
'el hombre': 'the man',
'el hermano': 'the brother',
'la hermana': 'the sister',
'el joven': 'the young man',
'la joven': 'the young woman',
'el lápiz': 'the pencil',
'el libro': 'the book',
'la madre': 'the mother',
'mas': 'but',
'más': 'more',
'la mujer': 'the woman',
'nosotros tenemos': 'we have',
'el oro': 'gold',
'el padre': 'the father',
'los pantalones': 'the trousers',
'el papel': 'the paper',
'para': 'for/by',
'la plata': 'silver',
'la pluma': 'the pen',
'el sombrero': 'the hat',
'él tiene': 'he has',
'V. tiene': 'you (sing.) have',
'Vs. tienen': 'you (pl.) have',
'la tinta': 'the ink',
'el tintero': 'the inkstand',
'tener': 'to have/to possess',
'yo tengo': 'I have',
'el viejo': 'the old man',
'la vieja': 'the old woman',
'la virtud': 'virtue',
'alemán': 'German',
'beber': 'to drink',
'bien': 'well',
'café': 'coffee',
'cerveza': 'beer',
'clavel': 'carnation',
'cliente': 'client/customer',
'comer': 'to eat',
'escribir': 'to write',
'estudiar': 'to study',
'exportar': 'to export',
'extranjero': 'foreigner',
'ferretería': 'ironware',
'grande': 'large',
'grandes(pl)': 'large',
'hijo': 'son',
'hija': 'daughter',
'italiano': 'Italian',
'jardinero': 'gardener',
'leer': 'to read',
'mañana': 'morning/to-morrow',
'manzana': 'apple',
'máquina': 'machine',
'mesa': 'table',
'mi': 'my',
'mucho (m.)': 'much',
'mucha (f.)': 'much',
'muy': 'very',
'pera': 'pear',
'pero': 'but',
'pobre': 'poor',
'¿qué?': 'what?',
'que': 'that/who/which',
'rosa': 'rose',
'su': 'his/her/their',
'su … de V.': 'your',
'té': 'tea',
'el … de V.': 'your',
'vino': 'wine',
'violeta': 'violet',
'allí': 'there',
'aquí': 'here',
'buscar': 'to look for',
'caballo': 'horse',
'caja': 'box/case',
'el capital': 'the capital/money',
'la capital': 'the capital/town',
'comprender': 'to understand',
'copiador': 'copybook',
'creer': 'to believe/to think',
'dependiente': 'clerk',
'factura': 'invoice',
'fardo': 'bale',
'Francés': 'Frenchman',
'girar': 'to draw/(a bill of exchange)',
'el idioma': 'the language',
'Inglés': 'Englishman',
'inteligencia': 'intelligence',
'mal': 'badly',
'muselina': 'muslin',
'nunca': 'never',
'país': 'country',
'pequeño': 'little (adj.)',
'poco': 'little (adv. and subs.)',
'el porta-ramillete or florero': 'the flower-stand',
'¿quién?': 'who? whom?',
'seda': 'silk',
'socio': 'partner',
'solamente': 'only',
'sólo': '(adv.) only',
'el tema': 'the exercise',
'activo': 'active',
'ahora': 'now',
'un año': 'a year',
'aquel/ese (m.)': 'that',
'aquella/esa (f.)': 'that',
'bayeta': 'baize',
'célebre': 'celebrated',
'cima': 'top',
'criados': 'men-servants',
'criadas': 'maid-servants',
'el día': 'the day',
'ejército': 'army',
'encuadernado': 'bound: (of books)',
'escritorio': 'writing-desk',
'los fósforos': 'the matches',
'Gales': 'Wales',
'juventud': 'youth: young age.',
'el lacre': 'the sealing-wax',
'lectura': 'reading',
'limpiar': 'to clean',
'limpio': 'clean',
'mayormente': 'especially',
'médico': 'doctor',
'el monte': 'the mountain',
'la nieve': 'the snow',
'por tanto': 'therefore',
'puerta': 'door',
'siempre': 'always',
'sincero': 'sincere',
'soldado': 'soldier',
'terciopelo': 'velvet',
'vela': 'candle',
'ventana': 'window',
'alguno-a': 'some or any (s.)',
'algunos-as': 'some or any (pl.)',
'amarillo': 'yellow',
'barba/barbas': 'beard',
'barbilla/barba': 'chin',
'blanco': 'white',
'boca': 'mouth',
'cabello': 'hair',
'cabeza': 'head',
'café/castaño': 'brown: (dyed)',
'cepillo': 'brush',
'cualquiera (s.)': 'any (affirmative)',
'cualesquiera (pl.)': 'any (affirmative)',
'dientes': 'teeth',
'dinero': 'money',
'encarnado': 'red',
'escoba': 'broom',
'estampar': 'to print (calico)',
'la frente': 'the forehead',
'lengua': 'tongue',
'malo': 'bad/wicked',
'manteca': 'butter',
'moreno': 'brown/(natural colour)',
'(la) nariz': 'nose',
'necesitar': 'to want/to need/to be in want of.',
'ninguno-a (s.)': 'any (after a negative)',
'ningunos-as (pl.)': 'any (after a negative)',
'el ojo': 'the eye',
'padres': 'parents',
'percal': 'calico',
'queremos': 'we want ',
'querer': 'to want/to wish to have',
'ellos quieren': 'they want',
'yo quiero': 'I want',
'V. quiere': 'you want',
'regla': 'ruler',
'si': 'if',
'la tez': 'complexion',
'un poco de': 'a little/some/or any',
'verde': 'green',
'acabar de': 'to have just',
'almacén': 'warehouse',
'aprender': 'to learn',
'ayudar': 'to help',
'bañar': 'to wet/to bathe/to water',
'bicicleta': 'bicycle',
'certísimo': 'most certain',
'discípulo': 'pupil',
'disfrutar': 'to enjoy',
'él es/ella es': 'it is',
'ello (neuter)': 'it',
'este (m.)/esta (f.)': 'this',
'esto (neuter)': 'this',
'estos (m.)/estas (f.)': 'these',
'la fecha': 'the date',
'la gente': 'the people',
'hermosamente': 'beautifully',
'importancia': 'importance',
'La India': 'India',
'libre': 'free',
'maestro': 'master: teacher',
'la mayor parte': 'most: the majority',
'el mes': 'the month',
'mismo': 'same',
'novísimo': 'brand new',
'otro': 'other/another',
'el Sena': 'River Seine',
'el Tajo': 'River Tagus',
'el Támesis': 'River Thames',
'también': 'also/too',
'tienda': 'shop',
'ventaja': 'advantag',
'al por mayor/por menor': 'wholesale/retail',
'arroz': 'rice',
'artículo': 'article',
'asociación de obreros': 'trade union',
'blanquear': 'to bleach',
'ya caigo': 'I understand/I see',
'colocar': 'to place',
'conseguir': 'to ge',
'consignación': 'consignment',
'contenido': 'content',
'decadencia': 'decadence',
'delegado': 'delegate',
'demasiado': 'too/too much',
'difícil': 'difficult',
'driles labrados': 'figured drill',
'driles lisos': 'plain drill',
'entrar á reinar': 'to begin to reign',
'escoger/elegir': 'to choose/to select',
'extraño': 'strange/queer/funny',
'el germen': 'the germ',
'grueso': 'thick/stout',
'hallar': 'to find',
'ilustrado': 'enlightened',
'incluyendo': 'enclosing',
'limitar': 'to limit',
'mientrastanto': 'meanwhile',
'obtener': 'to get',
'peso': 'weight',
'poder': 'power',
'podríamos': 'we should be able to/might/could',
'próximo': 'next',
'rebaja': 'abatement',
'rebajar/reducir': 'reduce/to abate',
'reducción': 'abatement/reduction',
'reunión': 'meeting',
'salir': 'to come/to go/out',
'salir en': 'to come to',
'solo (adj.)': 'alone',
'sólo/solamente (adv.)': 'only',
'sujeto á': 'subject to',
'sumar': 'to add',
'tocino': 'bacon',
'tomar': 'to take',
'varios': 'several',
'verificarse': 'to take place',
'verse obligado á': 'to be compelled to',
'actual': 'present',
'al por mayor/por menor': 'wholesale/retail',
'arroz': 'rice',
'artículo': 'article',
'asociación de obreros': 'trade union',
'blanquear': 'to bleach',
'ya caigo': 'I understand: I see',
'colocar': 'to place',
'*conseguir': 'to get',
'consignación': 'consignment',
'contenido': 'contents',
'decadencia': 'decadence',
'delegado': 'delegate',
'demasiado': 'too: too much',
'difícil': 'difficult',
'driles labrados': 'figured drills',
'driles lisos': 'plain drills',
'entrar á reinar': 'to begin to reign',
'escoger/elegir': 'to choose/to select',
'extraño': 'strange/queer/funny',
'el germen': 'the germ',
'grueso': 'thick/stout',
'hallar': 'to find',
'ilustrado': 'enlightened',
'incluyendo': 'enclosing',
'limitar': 'to limit',
'mientrastanto': 'meanwhile',
'obtener': 'to get',
'peso': 'weight',
'poder': 'power',
'podríamos': 'we should be able to/might/could',
'próximo': 'next',
'rebaja': 'abatement',
'rebajar/reducir': 'reduce/to abate',
'reducción': 'abatement/reduction',
'reunión': 'meeting',
'salir': 'to come/to go/out',
'salir en': 'to come to',
'solo (adj.)': 'alone',
'sólo/solamente (adv.)': 'only',
'sujeto á': 'subject to',
'sumar': 'to add',
'tocino': 'bacon',
'tomar': 'to take',
'varios': 'several',
'verificarse': 'to take place',
'verse obligado á': 'to be compelled to'
}